<#
.SYNOPSIS
    注册 novel_workflow 每日自动备份到 Windows Task Scheduler.

.DESCRIPTION
    在 Windows Task Scheduler 注册一个名为 "NovelWorkflowBackup" 的每日任务,
    默认 03:00 触发, 对所有项目跑 `python novel.py backup <书> --clean`.

    注册后:
    - 任务名:    NovelWorkflowBackup
    - 触发器:    每天 03:00
    - 操作:      对 projects/ 下每个子目录跑 `python novel.py backup <书> --clean`
    - 输出日志:  logs/backup_task.log
    - 用户:      SYSTEM (无需登录)

    卸载:  Unregister-ScheduledTask -TaskName "NovelWorkflowBackup" -Confirm:$false
    查看:  Get-ScheduledTask -TaskName "NovelWorkflowBackup"
    立即跑: Start-ScheduledTask -TaskName "NovelWorkflowBackup"

.PARAMETER Time
    每日触发时间 (HH:mm 24h), 默认 03:00.

.EXAMPLE
    PS> .\scripts\install_backup_task.ps1
    注册每日 03:00 备份任务.

.EXAMPLE
    PS> .\scripts\install_backup_task.ps1 -Time 02:30
    注册每日 02:30 备份任务.
#>

[CmdletBinding(SupportsShouldProcess=$true, ConfirmImpact="Medium")]
param(
    [ValidatePattern("^\d{2}:\d{2}$")]
    [string]$Time = "03:00"
)

$ErrorActionPreference = "Stop"

# ---------- 0. 前置检查 ----------

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Resolve-Path (Join-Path $ScriptDir "..") | Select-Object -ExpandProperty Path
Set-Location $RepoRoot

Write-Host "[install_backup_task] repo root = $RepoRoot" -ForegroundColor Cyan

$pythonExe = (Get-Command python -ErrorAction SilentlyContinue).Source
if (-not $pythonExe) {
    throw "python not found in PATH. Install Python 3.10+ and add to PATH."
}
Write-Host "[install_backup_task] python = $pythonExe"

$projectsDir = Join-Path $RepoRoot "projects"
if (-not (Test-Path $projectsDir)) {
    throw "projects/ not found at $projectsDir. Run from novel_workflow repo root."
}

try {
    & python novel.py backup --help 2>&1 | Out-Null
} catch {
    throw "novel.py backup failed. Check Python deps: pip install -r requirements.txt"
}

# ---------- 1. 构造 PowerShell 动作脚本 ----------

$actionPs1 = Join-Path $RepoRoot "scripts\run_backup_all.ps1"
$actionDir = Split-Path $actionPs1 -Parent
if (-not (Test-Path $actionDir)) {
    New-Item -ItemType Directory -Path $actionDir -Force | Out-Null
}

# 嵌入的动作脚本: 全部用 $` 转义 (PowerShell literal expansion 关闭)
$actionContent = @"
# Auto-generated by install_backup_task.ps1
# Runs novel backup <book> --clean for every project under projects/

`$ErrorActionPreference = "Continue"
`$RepoRoot = "__REPO_ROOT__"
`$LogFile = Join-Path `$RepoRoot "logs\backup_task.log"
`$LogDir = Split-Path `$LogFile -Parent

if (-not (Test-Path `$LogDir)) { New-Item -ItemType Directory -Path `$LogDir -Force | Out-Null }

function Write-Log(`$msg) {
    `$ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Add-Content -Path `$LogFile -Value "[`$ts] `$msg"
    Write-Host "[`$ts] `$msg"
}

Set-Location `$RepoRoot

`$projectsDir = Join-Path `$RepoRoot "projects"
if (-not (Test-Path `$projectsDir)) {
    Write-Log "ERROR: projects/ not found, aborting"
    exit 1
}

`$books = Get-ChildItem `$projectsDir -Directory | Where-Object { `$_.Name -notin @("nonexistent*", "不存在*", "测试书籍") }
if (-not `$books) {
    Write-Log "No books found under projects/, nothing to back up"
    exit 0
}

`$ok = 0
`$fail = 0
foreach (`$book in `$books) {
    `$name = `$book.Name
    Write-Log "Backing up `$name ..."
    try {
        `$output = & python novel.py backup `$name --clean 2>&1
        `$lastLine = (`$output | Select-Object -Last 1)
        if (`$LASTEXITCODE -eq 0) {
            Write-Log "  OK: `$name (`$lastLine)"
            `$ok++
        } else {
            Write-Log "  FAIL (`$LASTEXITCODE): `$name - `$lastLine"
            `$fail++
        }
    } catch {
        Write-Log "  EXCEPTION: `$name - `$_"
        `$fail++
    }
}

Write-Log "Backup run finished: `$ok ok, `$fail failed"
exit 0
"@

# 注入实际路径
$actionContent = $actionContent.Replace("__REPO_ROOT__", $RepoRoot)

# 写动作脚本 (UTF-8 with BOM, PowerShell 5.1 友好)
[System.IO.File]::WriteAllText($actionPs1, $actionContent, [System.Text.Encoding]::UTF8)
Write-Host "[install_backup_task] wrote $actionPs1"

# ---------- 2. 注册 Scheduled Task ----------

$taskName = "NovelWorkflowBackup"
$hour, $minute = $Time -split ":"

if (-not $WhatIfPreference) {
    $existing = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
    if ($existing) {
        Write-Host "[install_backup_task] task '$taskName' exists, updating..." -ForegroundColor Yellow
        Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
    }
} else {
    Write-Host "[WhatIf] Would check for existing task: $taskName" -ForegroundColor Yellow
}

$action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$actionPs1`""

$trigger = New-ScheduledTaskTrigger -Daily -At "$Time"
$trigger.Repetition = $null
$trigger.StartBoundary = (Get-Date -Hour $hour -Minute $minute -Second 0).ToString("yyyy-MM-ddTHH:mm:ss")

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Hours 1)

$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest

if ($PSCmdlet.ShouldProcess("ScheduledTask:$taskName @ $Time", "Register")) {
    Register-ScheduledTask `
        -TaskName $taskName `
        -Action $action `
        -Trigger $trigger `
        -Settings $settings `
        -Principal $principal `
        -Description "novel_workflow 每日自动备份 (所有书 projects/*/backups/), 默认 $Time" |
        Out-Null
} else {
    Write-Host "[WhatIf] Would register task: $taskName @ $Time" -ForegroundColor Yellow
}

# ---------- 3. 验证 + 报告 ----------

if ($WhatIfPreference) {
    Write-Host ""
    Write-Host "===== WhatIf 模式 (未真注册) =====" -ForegroundColor Yellow
    Write-Host ("  would-be 任务名:   " + $taskName)
    Write-Host ("  would-be 触发时间: 每天 " + $Time)
    Write-Host "  去掉 -WhatIf 参数重跑以真注册."
    Write-Host ""
    Write-Host "动作脚本生成 OK, 可手动运行:" -ForegroundColor Green
    Write-Host ("  " + $actionPs1)
    exit 0
}

$verify = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
Write-Host ""
Write-Host "===== 安装完成 =====" -ForegroundColor Green
Write-Host "  任务名:    $($verify.TaskName)"
Write-Host "  状态:      $($verify.State)"
Write-Host "  下次运行:  $(($verify | Get-ScheduledTaskInfo).NextRunTime)"
Write-Host "  触发时间:  每天 $Time"
Write-Host "  操作脚本:  $actionPs1"
Write-Host "  输出日志:  $RepoRoot\logs\backup_task.log"
Write-Host ""
Write-Host "手动测试:"
Write-Host '  Start-ScheduledTask -TaskName ''NovelWorkflowBackup'''
Write-Host ""
Write-Host "卸载:"
Write-Host '  Unregister-ScheduledTask -TaskName ''NovelWorkflowBackup'' -Confirm:$false'
