# Auto-generated by install_backup_task.ps1
# Runs novel backup <book> --clean for every project under projects/

$ErrorActionPreference = "Continue"
$RepoRoot = "D:\.openclaw\workspace\novel_workflow"
$LogFile = Join-Path $RepoRoot "logs\backup_task.log"
$LogDir = Split-Path $LogFile -Parent

if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Path $LogDir -Force | Out-Null }

function Write-Log($msg) {
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Add-Content -Path $LogFile -Value "[$ts] $msg"
    Write-Host "[$ts] $msg"
}

Set-Location $RepoRoot

$projectsDir = Join-Path $RepoRoot "projects"
if (-not (Test-Path $projectsDir)) {
    Write-Log "ERROR: projects/ not found, aborting"
    exit 1
}

$books = Get-ChildItem $projectsDir -Directory | Where-Object { $_.Name -notin @("nonexistent*", "不存在*", "测试书籍") }
if (-not $books) {
    Write-Log "No books found under projects/, nothing to back up"
    exit 0
}

$ok = 0
$fail = 0
foreach ($book in $books) {
    $name = $book.Name
    Write-Log "Backing up $name ..."
    try {
        $output = & python novel.py backup $name --clean 2>&1
        $lastLine = ($output | Select-Object -Last 1)
        if ($LASTEXITCODE -eq 0) {
            Write-Log "  OK: $name ($lastLine)"
            $ok++
        } else {
            Write-Log "  FAIL ($LASTEXITCODE): $name - $lastLine"
            $fail++
        }
    } catch {
        Write-Log "  EXCEPTION: $name - $_"
        $fail++
    }
}

Write-Log "Backup run finished: $ok ok, $fail failed"
exit 0